In [1]:
import torch

In [29]:
a = torch.tensor(2.)

In [33]:
a.requires_grad = True

In [34]:
b = a**2 + 1
b.requires_grad

True

In [35]:
b

tensor(5., grad_fn=<AddBackward0>)

In [36]:
b.backward()

In [38]:
a.grad

tensor(4.)

In [39]:
# 一维以上张量求导
a = torch.tensor([1., 2.], requires_grad=True)
b = a**2 + 1
b

tensor([2., 5.], grad_fn=<AddBackward0>)

In [42]:
b.is_leaf

False

In [45]:
# 叶子节点不能进行原位操作，如果进行原位操作，数据的值会被改变，但是反向传播会用到叶子节点的数据，会根据叶子节点的地址来取出叶子节点的值，叶子节点值的改变会导致计算错误。
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)

a = torch.mul(w, x)
b = torch.add(w, 1)

y0 = torch.mul(a, b)
y1 = torch.add(a, b)
loss = torch.cat([y0, y1], dim=0)
grad_tensor = torch.tensor([1., 2.]) # 多个梯度，权重的设置

loss.backward(gradient=grad_tensor)

w.grad

tensor([12.])

In [74]:
x = torch.tensor([3.], requires_grad=True)
y = torch.pow(x, 3)

grad_1 = torch.autograd.grad(y, x, create_graph=True)
grad_1

(tensor([27.], grad_fn=<MulBackward0>),)

In [2]:
grad_2 = torch.autograd.grad(grad_1[0], x)
grad_2

NameError: name 'grad_1' is not defined

In [7]:
a = torch.tensor([2.], requires_grad=True)

b = torch.tensor([3.], requires_grad=False)

c = 2* (a*b)
print(c)

c.backward()

print(a.grad)
print(b.grad)

tensor([12.], grad_fn=<MulBackward0>)
tensor([6.])
None
